name: Build, Lint and Test

on:
  workflow_dispatch: 

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.2

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run:  |
        go build -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Run go test
      run: go test ./...
    
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.7.0
      with:
        version: v1.54.2
        args: --exclude-use-default
        skip-pkg-cache: false
